### ISSUE TITLE
Cannot find icon: /Resources/icons/Maker_workbench_icon.svg

### ISSUE THREAD

**Issue by TankyTurk** [URJCMakerGroup/MakerWorkbench#20]
As instructed on Youtube I like to report an issue I am having since I installed Maker Workbench yesterday. I keep getting "/Resources/Icons/Maker_workbench_icon.svg" pop-up message and a "Cannot find icon: /Resources/icons/Maker_workbench_icon.svg" in the "Report View". This happens when I start Freecad and also when I open and existing project. It does not pop-up when I create a new project. The Maker Workbench still works but the pop-ups are annoying.

**Comment by allanlaal** [comment]
also visible when FreeCAD is launched from terminal

@TankyTurk could you edit the title to: `Cannot find icon: /Resources/icons/Maker_workbench_icon.svg`

**Comment by TankyTurk** [comment]
Done, hope it's ok now

**Comment by sepp2gl** [comment]
I had the same issue by today and for whatever reason I could not read the commits before.
So to me the issue still seems unsolved.
What I did to recover this workbench is to modify it's InitGui.py:
I simply replaced the path "/Ressource/icons/..." by the absolute path "/home/.../.FreeCAD/Mods/MakerWorkbench/Ressource/...".
Also this might only indicate, that I have an issue with the settings of python to handle relative paths correctly.
But as I'm not a python-expert, I don't know, how to solve it.

**Comment by luzpaz** [comment]
Please fix, this issues is confusing newbs on the FreeCAD forum, ref: https://forum.freecadweb.org/viewtopic.php?f=4&t=71278

**Comment by davidmubernal** [comment]
It took a long time, but I'm back. It should be fixed

**Comment by gigafresnel** [comment]
`[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3D_Printing_Tools
  * A2plus 0.4.59e
  * AnimationFreeCAD 1.0.0
  * Assembly3 0.11.3
  * Assembly4 0.12.4
  * CommandPanel
  * CubeMenu
  * CurvedShapes 1.0.4
  * Curves 0.5.12
  * Defeaturing 1.2.0
  * OpticsWorkbench 1.0.9
  * yaml-workspace 0.1.2
[/code]
`
I have the `File does not exist! /app/Mod/AnimationFreeCAD/icons/clapCinema.svg` error again. How to fix it ?

**Comment by luzpaz** [comment]
@gigafresnel What version of the workbench are you using ?

**Comment by gigafresnel** [comment]
> @gigafresnel What version of the workbench are you using ?

Where do I get this information from? Maybe it should be in the “Installed mods” list? Or is there any component used by one of the mentioned?

**Comment by luzpaz** [comment]
Sorry, there is no version info since there is no `package.xml` file. Therefore I opened a PR to add one in #26
